adminUser:
  password: vault:beakjasper/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:beakjasper/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:beakjasper/prow:hmacToken
segmentWriteKey: vault:beakjasper:segmentWriteKey
